excluded:
 - build/
 - DerivedData/

opt_in_rules: all
analyzer_rules: all
 
indentation_width:
  indentation_width: 4

line_length:
  warning: 141

disabled_rules:
  - accessibility_label_for_image
  - anonymous_argument_in_multiline_closure
  - attributes
  - blanket_disable_command
  - closure_body_length
  - contrasted_opening_brace
  - direct_return
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - identifier_name
  - missing_docs
  - multiline_function_chains
  - multiple_closures_with_trailing_closure
  - nesting
  - no_empty_block
  - no_grouping_extension
  - no_magic_numbers
  - one_declaration_per_file
  - opening_brace
  - prefixed_toplevel_constant
  - required_deinit
  - sorted_enum_cases
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - trailing_comma
  - trailing_whitespace
  - type_contents_order
  - vertical_whitespace
